### ISSUE TITLE
Tests failing when no environment variable present

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/cloud_watch#3]
```
Traceback (most recent call last):
  File "/opt/python3.4/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/cloud_watch/tests/test_cloud_watch.py", line 143, in test_error_connecting
    connect_func.return_value = CloudWatchConnection()
  File "/opt/python3.4/lib/python3.4/site-packages/boto/ec2/cloudwatch/__init__.py", line 102, in __init__
    profile_name=profile_name)
  File "/opt/python3.4/lib/python3.4/site-packages/boto/connection.py", line 1096, in __init__
    profile_name=profile_name)
  File "/opt/python3.4/lib/python3.4/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/opt/python3.4/lib/python3.4/site-packages/boto/auth.py", line 975, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

**Comment by mattdodge** [comment]
fixed by #4
